"""
## Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?




Link: https://projecteuler.net/problem=44

Date solved:  
2022/07/10
"""


ANSWER = 5482660

# imports

from maths.sequences import PentagonalNumbers

# solution


def solution():

    n = 1
    pentagonals = set()

    while True:
        H = PentagonalNumbers.formula(n)
        for M in pentagonals:
            L = H - M
            if L in pentagonals:
                D = M - L
                if D in pentagonals:
                    return D
        pentagonals.add(H)
        n += 1


if __name__ == "__main__":
    from time import perf_counter

    t0 = perf_counter()
    sol = solution()
    t1 = perf_counter()
    print(f"solution = {sol} in {t1-t0: 0.4f} seconds")
    print("answer   =", ANSWER)
