name: project-tests

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:

  test-modules:
    name: module-tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-modules

  test_answers_00s:
    name: answers-00s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=00s.py

  test_answers_10s:
    name: answers-10s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=10s.py
  
  test_answers_20s:
    name: answers-20s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=20s.py

  test_answers_30s:
    name: answers-30s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=30s.py

  test_answers_40s:
    name: answers-40s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=40s.py

  test_answers_50s:
    name: answers-50s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=50s.py
  
  test_answers_60s:
    name: answers-60s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=60s.py
  
  test_answers_70s:
    name: answers-70s
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies
        run: 
          pipenv install --dev --skip-lock
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run:
          make test-answers group=70s.py

  # run-linters:
  #   name: Run linters
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     # Setup Python (faster than using Python container)
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.9"

  #     - name: Install Python dependencies
  #       run: pip install black flake8

  #     - name: Run linters
  #       uses: wearerequired/lint-action@v2
  #       with:
  #         black: true
  #         flake8: true